name: Deploy to EC2 directly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<EC2_IP> "
          cd /path/to/project &&
          git pull origin main &&
          npm install &&
          npm run build &&
          pm2 restart app
          "
